services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: tblynxx
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  anagracetech-api:
    container_name: anagracetech-api
    image: tblynxx94/anagracetech-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db
    restart: unless-stopped


  anagracetech-react:
    container_name: anagracetech-react
    image: tblynxx94/anagracetech-react
    build:
      context: frontend/react
    ports:
      - "3000:5173"
    depends_on:
      - anagracetech-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
  pgadmin: